plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - INDEX.md
title: Stage Hacks
description: Tools for making performances work better.
theme: jekyll-theme-slate
